### ISSUE TITLE
INFO field reset by SPIP

### ISSUE THREAD

**Issue by chadisaad** [raphaelleman/SPiP#4]
In the last version (1.0), if we use an VCF input file, the INFO column is reset, and we lose all previous INFO fields. Only SPIP results are printed.

Is it possible to keep these informations (INFO column), and append SPIP infos (like in v0.5) ?

**Comment by raphaelleman** [comment]
After the version 0.6, the VCF output was formatted to be readable by the most of VCF aligner. However, the IDs of INFO column of input VCF can conflict with the SPiP INFO output. Thus as several prediction tools (ex: SpliceAI, AlamutBatch, Branchpointer, ...), the output contains only the SPiP predictions. 
If you wish to keep your VCF annotation plus the SPiP predictions, you can save the SPiP results in tabulated text format:
`Rscript ./SPiPv1.0.r -I /path/to/input.vcf -O /path/to/output.txt -s /path/to/samtools -f /path/to/genome.fa`
The output will merge the input VCF file and the SPiP annotations.
