### ISSUE TITLE
Probleme dans la v2 avec soumission sous format vcf pour certain variants

### ISSUE THREAD

**Issue by wcarre** [raphaelleman/SPiP#6]
Erreur dans la v2 pour certains variants soumis sous format vcf. Certains fonctionnent parfaitement, d'autre pas.
ma ligne de commande est :
Rscript /ngs/programs/SPiP/SPiPv2.0_main.r -I test.hg19.txt -O ./output_test_txt.v2.txt --GenomeAssenbly hg19  --transcriptome /ngs/bio-databases/SPiP/transcriptome_hg19.RData

input vcf :
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr7	44298527	NM_172079:c.221-2A>G	T	C	.	.	.

Sortie SPiP v2 :
CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	varID	Interpretation	InterConfident	SPiPscore	strand	gNomen	varType	ntChange	ExonInfo	exonSize	transcript	gene	NearestSS	DistSS	RegType	SPiCEproba	SPiCEinter_2thr	deltaMES	BP	mutInPBarea	deltaESRscore	posCryptMut	sstypeCryptMut	probaCryptMut	classProbaCryptMut	nearestSStoCrypt	nearestPosSStoCrypt	nearestDistSStoCrypt	posCryptWT	probaCryptWT	classProbaCryptWT	posSSPhysio	probaSSPhysio	classProbaSSPhysio	probaSSPhysioMut	classProbaSSPhysioMut
chr7	44298527	NM_172079:c.221-2A>G	T	C	.	.	.	no sequence:44298527	NA	-1	-1	NA	NA	NA	NA	NA	   0	NA	NA	NA	-1	NA	NA	NA	-1	NA	NA	-1	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	0	NA	NA	NA

Sortie SPiP v1.1 :
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	varID	Interpretation	InterConfident	chr	strand	gNomen	varType	ntChange	ExonInfo	transcript	gene	NearestSS	DistSS	RegType	seqPhysio	seqMutated	SPiCEproba	SPiCEinter_2thr	deltaMES	mutInPBarea	deltaESRscore	posCryptMut	sstypeCryptMut	probaCryptMut	classProbaCryptMut	nearestSStoCrypt	nearestPosSStoCrypt	nearestDistSStoCrypt	posCryptWT	probaCryptWT	classProbaCryptWT	posSSPhysio	probaSSPhysio	classProbaSSPhysio	probaSSPhysioMut	classProbaSSPhysioMut
chr7	44298527	NM_172079:c.221-2A>G	T	C	.	.	.1	NM_001220:g.44298527:A>G	Alter by SPiCE	98.67 % [96.17 % - 99.55 %]	chr7	-	44298527	substitution	A>G	Intron 3 (4078)	NM_001220	CAMK2B	acceptor	-2	IntronCons	CTCTGGCCTGCCCACCCGGGCCCTACCCAGCCCGATCCTCTGGGCAGCCCTAGGGCTTACACCGCTGGTGGTGTGCCTGGACAGGTACGGAGGCAGGCAGGAGGTGTGTCCTGGGCTATTGCCAGCCCCTCATGGCTTCTCTGTCCCCACAGTGCGTCTCCACGACAGCATCTCCGAGGAGGGCTTCCACTACCTGGTCTTCGATCTGTAAGTTCCAGAGCTGGGGACTCTCGCTGCACTCACTCCCAGCCTTGGCTCAGGGTGGGATCTGCAGCCTCCCCAGCCCCAGGGAATAGTCCCT	CTCTGGCCTGCCCACCCGGGCCCTACCCAGCCCGATCCTCTGGGCAGCCCTAGGGCTTACACCGCTGGTGGTGTGCCTGGACAGGTACGGAGGCAGGCAGGAGGTGTGTCCTGGGCTATTGCCAGCCCCTCATGGCTTCTCTGTCCCCACGGTGCGTCTCCACGACAGCATCTCCGAGGAGGGCTTCCACTACCTGGTCTTCGATCTGTAAGTTCCAGAGCTGGGGACTCTCGCTGCACTCACTCCCAGCCTTGGCTCAGGGTGGGATCTGCAGCCTCCCCAGCCCCAGGGAATAGTCCCT	0.99979	high	0	No	NA	0	No site	0	No	No site	0	0	0	0	No	0	0	No	0	No

Sortie SPiP v1.3 : 
varID	Interpretation	InterConfident	SPiPscore	chr	strand	gNomen	varType	ntChange	ExonInfo	exonSize	transcript	gene	NearestSS	DistSS	RegType	seqPhysio	seqMutated	SPiCEproba	SPiCEinter_2thr	deltaMES	BP	mutInPBarea	deltaESRscore	posCryptMut	sstypeCryptMut	probaCryptMut	classProbaCryptMut	nearestSStoCrypt	nearestPosSStoCrypt	nearestDistSStoCrypt	posCryptWT	probaCryptWT	classProbaCryptWT	posSSPhysio	probaSSPhysio	classProbaSSPhysio	probaSSPhysioMut	classProbaSSPhysioMut
NM_001220:g.44298527:A>G	Alter by SPiCE	98.54 % [94.83 % - 99.82 %]	0.860	chr7	-	44298527	substitution	A>G	Intron 3	4078	NM_001220	CAMK2B	acceptor	-2	IntronCons	CTCTGGCCTGCCCACCCGGGCCCTACCCAGCCCGATCCTCTGGGCAGCCCTAGGGCTTACACCGCTGGTGGTGTGCCTGGACAGGTACGGAGGCAGGCAGGAGGTGTGTCCTGGGCTATTGCCAGCCCCTCATGGCTTCTCTGTCCCCACAGTGCGTCTCCACGACAGCATCTCCGAGGAGGGCTTCCACTACCTGGTCTTCGATCTGTAAGTTCCAGAGCTGGGGACTCTCGCTGCACTCACTCCCAGCCTTGGCTCAGGGTGGGATCTGCAGCCTCCCCAGCCCCAGGGAATAGTCCCT	CTCTGGCCTGCCCACCCGGGCCCTACCCAGCCCGATCCTCTGGGCAGCCCTAGGGCTTACACCGCTGGTGGTGTGCCTGGACAGGTACGGAGGCAGGCAGGAGGTGTGTCCTGGGCTATTGCCAGCCCCTCATGGCTTCTCTGTCCCCACGGTGCGTCTCCACGACAGCATCTCCGAGGAGGGCTTCCACTACCTGGTCTTCGATCTGTAAGTTCCAGAGCTGGGGACTCTCGCTGCACTCACTCCCAGCCTTGGCTCAGGGTGGGATCTGCAGCCTCCCCAGCCCCAGGGAATAGTCCCT	0.99979	high	0	0	No	10	0	No site	0	No	No site	0	0	0	0	No	0	0	No	0	No

Si le même variant est soumis sous format txt en v2 :
input txt
gene	varID
CAMK2B	NM_172079:c.221-2A>G

sortie SPiP v2 :
gene	varID	Interpretation	InterConfident	SPiPscore	strand	gNomen	varType	ntChange	ExonInfo	exonSize	transcript	gene	NearestSS	DistSS	RegType	SPiCEproba	SPiCEinter_2thr	deltaMES	BP	mutInPBarea	deltaESRscore	posCryptMut	sstypeCryptMut	probaCryptMut	classProbaCryptMut	nearestSStoCrypt	nearestPosSStoCrypt	nearestDistSStoCrypt	posCryptWT	probaCryptWT	classProbaCryptWT	posSSPhysio	probaSSPhysio	classProbaSSPhysio	probaSSPhysioMut	classProbaSSPhysioMut
CAMK2B	NM_172079:c.221-2A>G	Alter by SPiCE	98.41 % [91.47 % - 99.96 %]	1	-	44298527	substitution	A>G	Intron 3	4078	NM_172079	CAMK2B	acceptor	-2	IntronCons	0.99979	high	0	0	No	10	0	No site	0	No	No site	0	0	0	0	No	0	0	No	0	No

Merci du retour.

**Comment by raphaelleman** [comment]
Bonjour,
Je vous ai envoyé un mail pour détaillé le problème. Brièvement ce type d'erreur ne devrait plus ré-apparaître sur la v2.1
Cordialement
