### ISSUE TITLE
Bug with a "big" allele

### ISSUE THREAD

**Issue by yannisduffourd** [raphaelleman/SPiP#9]
Hello, 

we encountered a bug while running SPIP on a ES VCF. 

The error was not really explicit : 

>  2023-03-27 14:44:29 Score Calculation... 
Erreur dans data.frame(..., check.names = FALSE) : 
  les arguments impliquent des nombres de lignes différents : 2429, 2430
Appels : cbind -> cbind -> data.frame
De plus : Il y a eu 50 avis ou plus (utilisez warnings() pour voir les 50 premiers)
Exécution arrêtée
spip exit code : 1

Sorry for the french R messages, but I know you can read it ;)
We had some troubles to identify why it stopped like that. But we did identified the VCF entry which caused the issue : 

the original VCF line was : 

> chr6    32517766    rs143960829    G    A,GTGTTGTTTTCAGACATGGCTCTACTAACAGCTTCTTTCCCCCTCTTTCAGGGACTCAGATGAAAGCAGTACAGGAAGAAGAAAAACAAGTTGCTAAGTCTCCCTGAGCCAATACTACTGCAGAATCCTGCAGAGACACAA    22250.88    SnpCluster    AC=2,1;AF=0.250,0.125;AN=8;BATCH_AC=12,1;BATCH_AF=0.261,0.022;BATCH_AN=46;BATCH_GTC=1/2:1|0/0:15|1/1:4|0/1:3;BATCH_GTN=23;BATCH_VARC=8,1;BaseQRankSum=0.722;CTRL_AC=36,0;CTRL_AF=0.180,0.000;CTRL_AN=200;CTRL_GTC=1/1:13|0/0:77|0/1:10;CTRL_GTN=100;CTRL_VARC=23,0;ClippingRankSum=0.00;DB;DP=100;ExcessHet=0.0002;FS=1.448;InbreedingCoeff=0.4592;MQ=43.30;MQRankSum=-1.000e+00;QD=23.94;ReadPosRankSum=0.927;SOR=0.847;ANN=A|intron_variant|MODIFIER|HLA-DRB5|HLA-DRB5|transcript|NM_002125|protein_coding|5/5|c.788-14C>T||||||,GTGTTGTTTTCAGACATGGCTCTACTAACAGCTTCTTTCCCCCTCTTTCAGGGACTCAGATGAAAGCAGTACAGGAAGAAGAAAAACAAGTTGCTAAGTCTCCCTGAGCCAATACTACTGCAGAATCCTGCAGAGACACAA|intron_variant|MODIFIER|HLA-DRB5|HLA-DRB5|transcript|NM_002125|protein_coding|5/5|c.788-15_788-14insTTGTGTCTCTGCAGGATTCTGCAGTAGTATTGGCTCAGGGAGACTTAGCAACTTGTTTTTCTTCTTCCTGTACTGCTTTCATCTGAGTCCCTGAAAGAGGGGGAAAGAAGCTGTTAGTAGAGCCATGTCTGAAAACAACA||||||;gnomADex_AC=.,.;gnomADex_AN=.;gnomADex_nhomalt=.,.;gnomADge_AC=823,.;gnomADge_AN=36652;gnomADge_nhomalt=2,.    GT:AD:DP:GQ:PGT:PID:PL    1/2:0,29,0:36:99:.:.:2265,879,780,1195,0,1115    0/1:5,25,0:30:99:0|1:32517690_A_C:1077,0,132,1092,210,1302    0/0:17,17,17:34:.:.:.:0,0,0,0,0,0    0/0:0,0,0:0:.:.:.:0,0,0,0,0,0

A big one for sure, so we simplified it in a version which still didn't work, and is repeatable and readable : 

> chr6    32517766    rs143960829    G    A,GTGTTGTTTTCAGACATGGCTCTACTAACAGCTTCTTTCCCCCTCTTTCAGGGACTCAGATGAAAGCAGTACAGGAAGAAGAAAAACAAGTTGCTAAGTCTCCCTGAGCCAATACTACTGCAGAATCCTGCAGAGACACAA    22250.88    SnpCluster    AC=2,1;AF=0.250,0.125    GT    1/2    0/1    0/0    0/0

After some tests, we tryed to modify manually (just for the tests) the size of the second alt allele obtaining : 
> chr6    32517766    rs143960829    G    A,GTGTTGTTTTCAGACATGGCTCTACTAACAGCTTCTTTCCCCCTCTTTCAGGGACTCAGATGAAAGCAGTACAGGAAGAAGAAAAACAAGTTGCTAAGTCTCCCTGAGCCAATACTACTGCAGAATCCTGCAGAGACA    22250.88    SnpCluster    AC=2,1;AF=0.250,0.125    GT    1/2    0/1    0/0    0/0

And this finally worked, with a 3 bases difference. 

So is there a defined limit in the alt allele size ? Is there also an issue with the multiallelic site ? 
If the limit is known, maybe it could be nice to perform a check of the alt allele length before running the process and crashing the whole job ?  

Thanks for your work.

**Comment by raphaelleman** [comment]
Hello,
Indeed the size of the insertion led to a bug for the score calculation as SPiP look for sequences +/-150 nt around the variant position. I have updated SPiP to skip this kind of variant and print a warning message.

Thanks for use SPiP

**Comment by apraga** [comment]
Hi,
I've also been bit by this issue but your latest commit solved it. Thanks !
